theme: jekyll-theme-minimal
# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: "Zahra Fazel"
#title: Blah
email: zahrafazel414@gmail.com
phone: +989134242696

# Social links
github_username:  ZahraFazel
# googlescholar_username: Gv9ET40AAAAJ
linkedin_username: zahra-fazel-0605b2109

# About Section
# about_title: About Me
about_profile_image: images/personal_photo.png
about_content: | # this will include new lines to allow paragraphs
  
  ​Hello! I'm Zahra Fazel, and I am a senior undergraduate student at the Sharif University of Technology. 
  My main interests are machine learning, deep learning, and their applications in computer vision, medical image analysis and natural language processing. 
  For more details, please see my **CV: [PDF](https://zahrafazel.github.io/files/CV.pdf)**.
  I intend to widen my knowledge in these areas by learning more about their theoretical and mathematical side and by practical exploitation of these methods in real-life problems. 
  My research goal is to introduce innovative approaches based on mathematical reasoning that solve practical problems in computer vision with a focus on medical applications.

# Education Section
# educaton_title: Education

# Research Section
# research_title: Research

# Teaching Section
# teaching_title: Teaching

# Work Section
# work_title: Work

# Accomplishments Section
# accomplishments_title: Accomplishments

# Footer
footer_show_references: true

# Build settings
remote_theme: ZahraFazel/ZahraFazel.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
